webtalk_init -webtalk_dir C:/FPGA_prj/UART_controller/UART_controller.sim/sim_1/behav/xsim/xsim.dir/UART_controller_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Oct 29 13:21:34 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "206282503_1777493521_210627251_460" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5dbf804a1b6b59879b37aa5b8582a303" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5cd55e03ecf847fe842b42f120d98db8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2712 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14392_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1684681553 -regid "206282503_1777493521_210627251_460" -xml C:/FPGA_prj/UART_controller/UART_controller.sim/sim_1/behav/xsim/xsim.dir/UART_controller_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/FPGA_prj/UART_controller/UART_controller.sim/sim_1/behav/xsim/xsim.dir/UART_controller_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/FPGA_prj/UART_controller/UART_controller.sim/sim_1/behav/xsim/xsim.dir/UART_controller_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
